mybatis-plus:
    mapper-locations: classpath:/mapper/xml/*.xml
    configuration:
        map-underscore-to-camel-case: true
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_mock?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone        =GMT%2B8&rewriteBatchedStatements=true
        username: root
        password: '097731'
        hikari:
            connection-timeout: 600000
            maximum-pool-size: 24
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8


