/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.nju.constant;

import java.util.Map;
import java.util.HashMap;

public class Constants {

  /**
   * 定义常量
   */
  public static final int INT32CONSTANTS = 9853;

  public static final Map<String,String> MAPCONSTANT = new HashMap<String,String>();
  static {
    MAPCONSTANT.put("hello", "world");
    MAPCONSTANT.put("goodnight", "moon");
  }

}
